#!/usr/bin/env -S d2 --watch --layout elk --center -s

start: "Start"
input: "Enter a number (n)"
condition1: "Is n ≤ 1?"
not_prime: "Not Prime"
loop_start: "Set i = 2"
condition2: "Is i * i ≤ n?"
check_div: "Is n % i == 0?"
increment: "Increment i (i = i + 1)"
prime: "Prime"
end: "End"

start -> input: "Start"
input -> condition1: "Enter"
condition1 -> not_prime: "Yes"
not_prime -> end: "End"

condition1 -> loop_start: "No"
loop_start -> condition2: "Set"
condition2 -> check_div: "Yes"

check_div -> not_prime: "Yes"
check_div -> increment: "No"
increment -> condition2: "Increment"

condition2 -> prime: "No"
prime -> end: "End"

start.shape: oval
start.style.stroke: deepskyblue
end.shape: oval
condition1.shape: diamond
condition2.shape: diamond
